import React from 'react';
import prisma from '@/lib/prisma';
import RecommendationActions from '@/components/grievance/RecommendationActions';
import { CheckCheck, CheckCircle2, XCircle, Clock, ArrowUpRight, Sparkles } from 'lucide-react';

export const dynamic = 'force-dynamic';

export default async function RecommendationsPage() {
  const recommendations = await prisma.recommendation.findMany({
    orderBy: { createdAt: 'desc' },
    include: {
      grievance: {
        include: { department: true, location: true },
      },
    },
  });

  return (
    <div className="space-y-6">
      <div className="border-b border-dark-800 pb-4">
        <div className="flex items-center gap-2">
          <h1 className="text-xl sm:text-2xl font-display font-black text-white uppercase tracking-tight flex items-center gap-2">
            <CheckCheck className="w-6 h-6 text-emerald-400" />
            <span>AI ADMINISTRATIVE DECISION & RECOMMENDATION ENGINE</span>
          </h1>
          <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
            Nodal Officer Action Center
          </span>
        </div>
        <p className="text-xs text-slate-400 mt-1">
          Automated recommendations generated by cross-analyzing SLA risk, routing deadlocks, and officer workload saturation.
        </p>
      </div>

      <div className="space-y-4">
        {recommendations.map((rec) => (
          <div
            key={rec.id}
            className="bg-dark-900 border border-dark-800 hover:border-gold-500/40 rounded-xl p-5 shadow-card-dark transition-all flex flex-col md:flex-row md:items-center justify-between gap-5"
          >
            <div className="space-y-2 flex-1">
              <div className="flex items-center gap-2.5">
                <span className="px-2.5 py-0.5 rounded bg-gold-500 text-black font-black text-[10px] uppercase tracking-wider font-mono">
                  {rec.type}
                </span>
                <span className="font-mono text-xs font-bold text-white">
                  {rec.grievance.grievanceNumber}
                </span>
                <span className="text-slate-500">•</span>
                <span className="text-xs text-slate-400">{rec.grievance.department.name}</span>
                <span className="ml-auto font-mono text-xs font-bold text-emerald-400 md:ml-2">
                  Confidence: {Math.round(rec.confidence * 100)}%
                </span>
              </div>

              <h3 className="text-base font-bold text-white">{rec.recommendation}</h3>

              <p className="text-xs text-slate-300 leading-relaxed bg-dark-950 p-3 rounded-lg border border-dark-800">
                Reasoning: <span className="text-slate-200">"{rec.reason}"</span>
              </p>
            </div>

            {/* Actions for Nodal Officer */}
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 flex-shrink-0">
              <RecommendationActions
                grievanceId={rec.grievance.id}
                grievanceNumber={rec.grievance.grievanceNumber}
                initialStatus={rec.status}
                actionTakenBy={rec.actionTakenBy}
                returnUrl="/dashboard/intelligence/recommendations"
                compact={true}
              />

              <a
                href={`/grievances/${rec.grievance.grievanceNumber}`}
                className="w-full sm:w-auto bg-dark-850 hover:bg-dark-800 text-gold-400 px-3 py-2 rounded-lg text-xs font-bold border border-dark-750 hover:border-gold-500/40 transition flex items-center justify-center gap-1"
              >
                <span>Review 360°</span>
                <ArrowUpRight className="w-3.5 h-3.5" />
              </a>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
